---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ubi8
spec:
  tags:
    - from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8
      name: latest
      importPolicy:
        scheduled: true
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ubi8-minimal
spec:
  tags:
    - from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8-minimal
      name: latest
      importPolicy:
        scheduled: true
---
kind: ImageStream
apiVersion: v1
metadata:
  name: quarkus-native-s2i
spec:
  tags:
    - name: "19.3"
      from:
        kind: DockerImage
        name: quay.io/quarkus/ubi-quarkus-native-s2i:19.3.1-java11
      importPolicy:
        scheduled: true
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: my-operator
spec: {}
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: my-operator-quarkus
spec: {}